# This file contains an example of the plotting configuration used for multigrid_stats.py

plots:
  - label: range 1 (no RFI no source)
    cubes:
      visgrid: rangeA/visgrid.rangeA6.dumpgrid
      pcfgrid: rangeA/pcfgrid.rangeA6.dumpgrid
  - label: range 2 (RFI)
    cubes:
      visgrid: rangeB/visgrid.rangeB6.dumpgrid
      pcfgrid: rangeB/pcfgrid.rangeB6.dumpgrid
  - label: range 3 (source with no RFI)
    cubes:
      visgrid: rangeC/visgrid.rangeC6.dumpgrid
      pcfgrid: rangeC/pcfgrid.rangeC6.dumpgrid
